services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-container
    ports:
      - '3005:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}

  mongodb:
    image: mongo:4.4
    container_name: mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
